status save 2017/05/25

diff --git a/cdist/conf/type/__install_reboot/gencode-remote b/cdist/conf/type/__install_reboot/gencode-remote
--- a/cdist/conf/type/__install_reboot/gencode-remote
+++ b/cdist/conf/type/__install_reboot/gencode-remote
@@ -20,4 +20,6 @@
 
 options="$(cat "$__object/parameter/options")"
 
-echo "reboot $options"
+set +e
+echo "reboot $options" || echo "errors can be ignored here"
+
