status save 2018/03/28

diff --git a/cdist/conf/type/__package/manifest b/cdist/conf/type/__package/manifest
--- a/cdist/conf/type/__package/manifest
+++ b/cdist/conf/type/__package/manifest
@@ -23,43 +23,51 @@
 # system.
 #
 
+##printf "DEBUG: %s - start\n" "${__type##*/}"
+
 type="$__object/parameter/type"
 
 if [ -f "$type" ]; then
-   type="$(cat "$type")"
+  type="$(cat "$type")"
 else
-   # By default determine package manager based on operating system
-   os="$(cat "$__global/explorer/os")"
-   case "$os" in
-         amazon|centos|fedora|redhat) type="yum" ;;
-         archlinux) type="pacman" ;;
-         debian|ubuntu|linaro) type="apt" ;;
-         freebsd) type="pkg_freebsd" ;;
-         gentoo) type="emerge" ;;
-         suse) type="zypper" ;;
-         openwrt) type="opkg" ;;
-         *)
-            echo "Don't know how to manage packages on: $os" >&2
-            exit 1
-         ;;
+  # By default determine package manager based on operating system
+  os="$(cat "$__global/explorer/os")"
+  case "$os" in
+    amazon|centos|fedora|redhat) type="yum" ;;
+    archlinux) type="pacman" ;;
+    debian|ubuntu|linaro) type="apt" ;;
+    freebsd) type="pkg_freebsd" ;;
+    gentoo) type="emerge" ;;
+    suse) type="zypper" ;;
+    openwrt) type="opkg" ;;
+    *)
+      echo "Don't know how to manage packages on: $os" >&2
+      exit 1
+    ;;
    esac
 fi
 
 state="$(cat "$__object/parameter/state")"
 
-set -- "$@" "$__object_id" "--state" "$state"
+__opts="$__object_id --state $state"
+
 cd "$__object/parameter"
-for property in $(ls .); do
-   [ "$property" = "ignoreerrors" ] && continue
-   if [ "$property" != "type" -a "$property" != "state" ]; then
-      set -- "$@" "--$property" "$(cat "$property")"
-   fi
+for property in $(ls .) ; do
+  case "${property}" in
+    type|state|ignoreerrors) continue ;;
+    unauthenticated)         opts="$__opts --unauthenticated"  ;;
+    *)                       opts="$__opts --$property $(cat "$property")"    ;;
+  esac
 done
 
+##printf "DEBUG: %s - setup with objectid=\"%s\", state=\"%s\"\n" "${__type##*/}" "$__object_id" "${state}"
+
+printf "DEBUG: %s - calling __package_%s %s\n" "${__type##*/}" "${type}" "`echo $__opts | tr [:space:] ' '`"
+
 if [ -f "$__object/parameter/ignoreerrors" ] ; then
-   __package_$type "$@" || echo "WARNING: __package_$type "$@" returned error code $?"
+   __package_$type $__opts || printf "WARNING: __package_%s \"%s\" returned error code %s\n" "${type}" "`echo $__opts | tr [:space:] ' '`"
 else
-   __package_$type "$@"
+   __package_$type $__opts
 fi
 
-
+##printf "DEBUG: %s - finished\n" "${__type##*/}"
diff --git a/cdist/conf/type/__package_apt/gencode-remote b/cdist/conf/type/__package_apt/gencode-remote
--- a/cdist/conf/type/__package_apt/gencode-remote
+++ b/cdist/conf/type/__package_apt/gencode-remote
@@ -21,10 +21,22 @@
 # Manage packages on Debian and co.
 #
 
+instopt="--allow-downgrades --allow-remove-essential --allow-change-held-packages"
+remopt=""
+
 if [ -f "$__object/parameter/name" ]; then
-   name="$(cat "$__object/parameter/name")"
+  name="$(cat "$__object/parameter/name")"
 else
-   name="$__object_id"
+  name="$__object_id"
+fi
+
+if [ -f "$__object/parameter/unauthenticated" ]; then
+  instopt="${instopt} --allow-unauthenticated"
+fi
+
+if [ -z "${name}" ] ; then
+  echo "WARNING: no package name defined , ignoring (args=\"$@\")"
+  exit 0
 fi
 
 if [ -f "$__object/parameter/state" ]; then
@@ -44,19 +56,23 @@ esac
 
 # Hint if we need to avoid questions at some point:
 # DEBIAN_PRIORITY=critical can reduce the number of questions
-aptget="DEBIAN_FRONTEND=noninteractive apt-get --quiet --yes --no-install-recommends -o DPkg::Options::=\"--force-confold\""
+aptget="DEBIAN_FRONTEND=noninteractive apt-get --quiet --yes --no-install-recommends \
+        -o DPkg::Options::=\"--force-confold\" \
+        -o DPkg::Options::=\"--force-depends\""
 
 [ "$state_is" = "$state_should" ] && exit 0
 
 case "$state_should" in
-    present)
-        echo $aptget install --force-yes \"$name\"
-    ;;
-    absent)
-        echo $aptget remove \"$name\"
-    ;;
-    *)
-        echo "Unknown state: $state_should" >&2
-        exit 1
-    ;;
+  present)
+    printf "%s install %s \"%s\"\n" "${aptget}" "${instopt}" "${name}" 2>&1 || printf "ERROR:%s install %s \"%s\" failed\n" "${aptget}" "${instopt}" "${name}"
+    ## echo $aptget install --allow-downgrades --allow-remove-essential --allow-change-held-packages \"$name\" 2>&1 || echo "ERROR
+  ;;
+  absent)
+    printf "%s remove %s \"%s\"\n" "${aptget}" "${remopt}" "${name}" 2>&1 || printf "ERROR:%s remove %s \"%s\" failed\n" "${aptget}" "${remopt}" "${name}"
+    ##echo $aptget remove ${remopt} \"$name\"
+  ;;
+  *)
+    echo "Unknown state: $state_should" >&2
+    exit 1
+  ;;
 esac
diff --git a/cdist/conf/type/__start_on_boot/gencode-remote b/cdist/conf/type/__start_on_boot/gencode-remote
--- a/cdist/conf/type/__start_on_boot/gencode-remote
+++ b/cdist/conf/type/__start_on_boot/gencode-remote
@@ -1,7 +1,7 @@
-#!/bin/sh
+#!/bin/sh -e
 #
 # 2012-2013 Nico Schottelius (nico-cdist at schottelius.org)
-# 2013 Daniel Heule (hda at sfs.biz)
+# 2016 Daniel Heule (hda at sfs.biz)
 #
 # This file is part of cdist.
 #
@@ -22,79 +22,99 @@
 
 state_should="$(cat "$__object/parameter/state")"
 state_is=$(cat "$__object/explorer/state")
+init=$(cat "$__global/explorer/init")
 target_runlevel="$(cat "$__object/parameter/target_runlevel")"
 
 # Short circuit if nothing is to be done
 [ "$state_should" = "$state_is" ] && exit 0
 
 os=$(cat "$__global/explorer/os")
+os_version=$(cat "$__global/explorer/os_version")
 name="$__object_id"
 
 case "$state_should" in
     present)
-        case "$os" in
-            archlinux)
-                echo "systemctl enable \"$name\""
-            ;;
-            debian)
-                echo update-rc.d -f \"$name\" enable
-            ;;
-            linaro|ubuntu)
-                echo "update-rc.d \"$name\" defaults >/dev/null"
-                echo "rm -f /etc/init/$name.override"
-            ;;
-            gentoo)
-                echo rc-update add \"$name\" \"$target_runlevel\"
-            ;;
+        if [ "$init" = 'systemd' ]; then
+            # this handles ALL linux distros with systemd
+            # e.g. archlinux, gentoo in some cases, new RHEL and SLES versions
+            echo "systemctl -q enable \"$name\""
+        else
+            case "$os" in
+                debian)
+                    case "$os_version" in
+                        [1-7]*)
+                            echo "update-rc.d \"$name\" defaults >/dev/null"
+                        ;;
+                        8*)
+                            echo "systemctl enable \"$name\""
+                        ;;
+                        *)
+                            echo "Unsupported version $os_version of $os" >&2
+                            exit 1
+                        ;;
+                    esac
+                ;;
+                devuan)
+                    echo "update-rc.d \"$name\" defaults >/dev/null"
+                ;;
 
-            amazon|centos|fedora|owl|redhat|suse)
-                echo chkconfig \"$name\" on
-            ;;
+                gentoo)
+                    echo rc-update add \"$name\" \"$target_runlevel\"
+                ;;
 
-            openwrt)
-                # 'enable' can be successful and still return a non-zero exit
-                # code, deal with it by checking for success ourselves in that
-                # case (the || ... part).
-                echo "/etc/init.d/\"$name\" enable || [ -f /etc/rc.d/S??\"$name\" ]"
-            ;;
+                amazon|scientific|centos|fedora|owl|redhat|suse)
+                    echo chkconfig \"$name\" on
+                ;;
 
-            *)
-               echo "Unsupported os: $os" >&2
-               exit 1
-            ;;
-        esac
+                openwrt)
+                    # 'enable' can be successful and still return a non-zero exit
+                    # code, deal with it by checking for success ourselves in that
+                    # case (the || ... part).
+                    echo "/etc/init.d/\"$name\" enable || [ -f /etc/rc.d/S??\"$name\" ]"
+                ;;
+
+                ubuntu)
+                    echo "update-rc.d \"$name\" defaults >/dev/null"
+                ;;
+
+                *)
+                   echo "Unsupported os: $os" >&2
+                   exit 1
+                ;;
+            esac
+        fi
     ;;
 
     absent)
-        case "$os" in
-            archlinux)
-                echo "systemctl disable \"$name\""
-            ;;
-            debian)
-                echo update-rc.d -f \"$name\" remove
-            ;;
-            linaro|ubuntu)
-                echo update-rc.d -f \"$name\" remove
-                echo "echo manual > /etc/init/$name.override"
-            ;;
-            gentoo)
-                echo rc-update del \"$name\"  \"$target_runlevel\"
-            ;;
+        if [ "$init" = 'systemd' ]; then
+            # this handles ALL linux distros with systemd
+            # e.g. archlinux, gentoo in some cases, new RHEL and SLES versions
+            echo "systemctl -q disable \"$name\""
 
-            centos|fedora|owl|redhat|suse)
-                echo chkconfig \"$name\" off
-            ;;
+        else
+            case "$os" in
+                debian|ubuntu|devuan)
+                    echo update-rc.d -f \"$name\" remove
+                ;;
 
-            openwrt)
-                echo "\"/etc/init.d/$name\" disable"
-            ;;
+                gentoo)
+                    echo rc-update del \"$name\"  \"$target_runlevel\"
+                ;;
 
-            *)
-               echo "Unsupported os: $os" >&2
-               exit 1
-            ;;
-        esac
- 
+                centos|fedora|owl|redhat|suse)
+                    echo chkconfig \"$name\" off
+                ;;
+
+                openwrt)
+                    echo "\"/etc/init.d/$name\" disable"
+                ;;
+
+                *)
+                   echo "Unsupported os: $os" >&2
+                   exit 1
+                ;;
+            esac
+        fi
     ;;
 
     *)
